name: Simple Intel - Watch CISA
on: 
  schedule:
    - cron:  '30 6 * * 1'      # Runs every Monday at 6:30.  See:  crontab.guru.
jobs:
  watch_cisa:
    runs-on: ubuntu-latest
    name: Simple Intel Watch CISA 
    steps:
    - name: Check out Repo
      uses: actions/checkout@v2
    - run: ./cisa-known-exploited.sh > cisa.txt
    - run: ./slackmessage.sh cisa.txt ${{ secrets.SLACK_WEBHOOK_URL }}
