# This is a basic workflow to help you get started with Actions
name: ZAP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
      branches: [ main ]
  schedule:
    # - cron:  '0 1 * * 1'      # Runs every day At 01:00.
    - cron:  '45 6 * * 1'      # Runs every Monday at 6:45.  See:  crontab.guru.

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan (Main website)
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://jemurai.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
